### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by mestia** [FCS-analysis/multipletau#10]
Hi Paul, 

Could you please have a look why the tests fail ? 
I've tested it on my build machine and get the same results.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813983

Thank you, 
Alex

**Comment by paulmueller** [comment]
Could you give me the output of `pip freeze`?
It looks like there is a new version of NumPy that isn't covered by my tests.

https://travis-ci.org/FCS-analysis/multipletau

**Comment by mestia** [comment]
that's is the output of pip freeze, though I do not use pip.

the version of NumPy is  1:1.11.0~b2-1
----

alabaster==0.7.6
apt-xapian-index==0.47
astroid==1.4.4
authprogs==0.5.1
autopep8==0.9.1
Babel==1.3
beautifulsoup4==4.4.1
bzr==2.7.0.dev1
bzr-builddeb==2.8.6
cairocffi==0.7.2
CairoSVG==1.0.19
cffi==1.5.0
chardet==2.3.0
configobj==5.0.6
cryptography==1.2.2
cycler==0.9.0
Cython==0.23.2
decorator==4.0.6
defusedxml==0.4.1
distro-info==0.14
docutils==0.12
enum34==1.1.2
funcsigs==0.4
gbp==0.7.2
gmpy==1.17
html5lib==0.999
httplib2==0.9.1
idna==2.0
ipaddress==1.0.16
ipython==2.4.1
Jinja2==2.8
keyring==7.3
launchpadlib==1.10.3
lazr.restfulclient==0.13.4
lazr.uri==1.0.3
lazy-object-proxy==1.2.1
libtiff==0.4.1.dev0
linecache2==1.0.0
lmfit==0.9.2
logilab-common==1.1.0
lxml==3.5.0
Magic-file-extensions==0.2
MarkupSafe==0.23
matplotlib==1.5.1rc1
mock==1.3.0
mockito==0.5.2
mpmath==0.19
mysql-connector-python==2.0.4
mysql-utilities==1.6.1
mysqlclient==1.3.7
ndg-httpsclient==0.4.0
nose==1.3.7
numpy==1.11.0b2
numpydoc==0.5
oauth==1.0.1
pbr==1.8.0
pep8==1.6.2
pexpect==4.0.1
Pillow==3.1.0
ply==3.7
ptyprocess==0.5
py==1.4.31
pyasn1==0.1.9
pychecker==0.8.19
pycparser==2.14
pycrypto==2.6.1
pycurl==7.21.5
pydns==2.3.6
pyglet==1.1.4
Pygments==2.1
pygobject==3.18.2
pygpgme==0.3
pyliblzma==0.5.3
pylint==1.5.2
pyOpenSSL==0.15.1
pyparsing==2.0.3
pytest==2.8.5
python-apt==1.1.0b1
python-dateutil==2.4.2
python-debian==0.1.27
python-debianbts==2.6.0
python-lzo==1.8
pytz==2012rc0
PyYAML==3.11
reportbug==6.6.6
requests==2.9.1
roman==2.0.0
scipy==0.17.0
selenium==2.48.0
simplegeneric==0.8.1
simplejson==3.8.1
SimPy==2.3.1
six==1.10.0
SOAPpy==0.12.22
Sphinx==1.3.5
sphinx-rtd-theme==0.1.9
splinter==0.7.2
stdeb==0.8.5
sympy==0.7.6.1
traceback2==1.4.0
ubuntu-dev-tools==0.155
unittest2==1.1.0
urllib3==1.13.1
wadllib==1.3.2
wheel==0.26.0
wrapt==1.8.0
wstools==0.4.3
wxPython==2.8.12.1
wxPython-common==2.8.12.1
xcffib==0.4.0
zope.interface==4.1.3

**Comment by paulmueller** [comment]
The release notes of numpy 1.11 

http://docs.scipy.org/doc/numpy-dev/release.html

states "Deprecated to error": "Indexing with floats raises IndexError, e.g., a[0, 0.0]."
I believe that is the problem.

I have converted all indices to `np.int`, so it might work now. I could not test with numpy 1.11 because it is not available at PyPI right now. Could you please check if it works now?

**Comment by mestia** [comment]
Thanks! the update has solved the problem.
